name: NYC-Env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.5
  - branca=0.5.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - cffi=1.15.0
  - charset-normalizer=2.1.0
  - cryptography=35.0.0
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.4
  - folium=0.12.1.post1
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.3
  - intel-openmp=2021.4.0
  - ipykernel=6.9.1
  - ipython=8.4.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.0
  - jpeg=9e
  - jupyter_client=7.2.2
  - jupyter_core=4.10.0
  - kiwisolver=1.4.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxml2=2.9.14
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - numexpr=2.8.3
  - numpy=1.22.3
  - numpy-base=1.22.3
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.3
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.1.2
  - plotly=5.9.0
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2022.1
  - pyzmq=23.2.0
  - qt=5.9.7
  - readline=8.1.2
  - requests=2.28.1
  - scikit-learn=1.1.1
  - scipy=1.7.3
  - seaborn=0.11.2
  - setuptools=61.2.0
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.38.5
  - stack_data=0.2.0
  - tenacity=8.0.1
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.1.1
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.12
  - zstd=1.5.2
